version: '3'
services:
    redis:
        image: redis:latest
        ports:
            - 6378:6378
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]